#ifndef ONTOLOGENIUS_DEPRECATED_MANAGERCLIENT_H
#define ONTOLOGENIUS_DEPRECATED_MANAGERCLIENT_H

#include "ontologenius/API/ontologenius/clients/ManagerClient.h"

#endif // ONTOLOGENIUS_DEPRECATED_MANAGERCLIENT_H
