#ifndef ONTOLOGENIUS_DEPRECATED_REASONERCLIENT_H
#define ONTOLOGENIUS_DEPRECATED_REASONERCLIENT_H

#include "ontologenius/API/ontologenius/clients/ReasonerClient.h"

#endif // ONTOLOGENIUS_DEPRECATED_REASONERCLIENT_H
