#ifndef ONTOLOGENIUS_DEPRECATED_ONTOLOGYCLIENT_H
#define ONTOLOGENIUS_DEPRECATED_ONTOLOGYCLIENT_H

#include "ontologenius/API/ontologenius/clients/ontologyClients/OntologyClient.h"

#endif // ONTOLOGENIUS_DEPRECATED_ONTOLOGYCLIENT_H
