#ifndef ONTOLOGENIUS_DEPRECATED_FEEDERPUBLISHER_H
#define ONTOLOGENIUS_DEPRECATED_FEEDERPUBLISHER_H

#include "ontologenius/API/ontologenius/FeederPublisher.h"

#endif // ONTOLOGENIUS_DEPRECATED_FEEDERPUBLISHER_H
